# Generated by Django 4.2.7 on 2026-06-13 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, unique=True, verbose_name='批次编号')),
                ('name', models.CharField(max_length=100, verbose_name='批次名称')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='采购日期')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='总数量')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '批次',
                'verbose_name_plural': '批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_no', models.CharField(max_length=50, unique=True, verbose_name='盒位编号')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='存放位置')),
                ('capacity', models.IntegerField(default=1, verbose_name='容量')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '存放盒位',
                'verbose_name_plural': '存放盒位',
                'ordering': ['box_no'],
            },
        ),
        migrations.CreateModel(
            name='Headphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=50, unique=True, verbose_name='耳机编号')),
                ('compatible_terminal', models.CharField(blank=True, max_length=100, verbose_name='适配终端')),
                ('responsible_person', models.CharField(blank=True, max_length=50, verbose_name='责任人')),
                ('status', models.CharField(choices=[('pending_borrow', '待领出'), ('in_use', '使用中'), ('pending_disinfect', '待消杀'), ('pending_review', '待复核'), ('available', '恢复可用'), ('out_of_service', '停用观察')], default='pending_borrow', max_length=20, verbose_name='状态')),
                ('battery_level', models.IntegerField(default=100, verbose_name='电量(%)')),
                ('earpad_damaged', models.BooleanField(default=False, verbose_name='耳罩破损')),
                ('last_borrow_time', models.DateTimeField(blank=True, null=True, verbose_name='上次领出时间')),
                ('last_return_time', models.DateTimeField(blank=True, null=True, verbose_name='上次归还时间')),
                ('current_borrower', models.CharField(blank=True, max_length=50, verbose_name='当前领用人')),
                ('suspend_reason', models.TextField(blank=True, verbose_name='停用说明')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='headphones', to='headphones.batch', verbose_name='所属批次')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='headphones', to='headphones.box', verbose_name='存放盒位')),
            ],
            options={
                'verbose_name': '耳机',
                'verbose_name_plural': '耳机',
                'ordering': ['serial_no'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('field_staff', '现场人员')], default='field_staff', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_time', models.DateTimeField(auto_now_add=True, verbose_name='复核时间')),
                ('passed', models.BooleanField(default=True, verbose_name='复核通过')),
                ('earpad_damaged', models.BooleanField(default=False, verbose_name='耳罩破损')),
                ('battery_ok', models.BooleanField(default=True, verbose_name='电量正常')),
                ('appearance_ok', models.BooleanField(default=True, verbose_name='外观正常')),
                ('function_ok', models.BooleanField(default=True, verbose_name='功能正常')),
                ('remark', models.TextField(blank=True, verbose_name='复核备注')),
                ('headphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='headphones.headphone', verbose_name='耳机')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
            ],
            options={
                'verbose_name': '复核记录',
                'verbose_name_plural': '复核记录',
                'ordering': ['-review_time'],
            },
        ),
        migrations.CreateModel(
            name='DisinfectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disinfect_time', models.DateTimeField(auto_now_add=True, verbose_name='消杀时间')),
                ('disinfect_method', models.CharField(default='酒精擦拭', max_length=100, verbose_name='消杀方式')),
                ('result', models.BooleanField(default=True, verbose_name='消杀结果')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('headphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disinfection_records', to='headphones.headphone', verbose_name='耳机')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='消杀操作人')),
            ],
            options={
                'verbose_name': '消杀记录',
                'verbose_name_plural': '消杀记录',
                'ordering': ['-disinfect_time'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.CharField(max_length=50, verbose_name='领用人')),
                ('borrow_time', models.DateTimeField(auto_now_add=True, verbose_name='领出时间')),
                ('expected_return_time', models.DateTimeField(blank=True, null=True, verbose_name='预计归还时间')),
                ('return_time', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('battery_before', models.IntegerField(blank=True, null=True, verbose_name='领出前电量(%)')),
                ('battery_after', models.IntegerField(blank=True, null=True, verbose_name='归还时电量(%)')),
                ('earpad_damaged_before', models.BooleanField(default=False, verbose_name='领出前耳罩破损')),
                ('earpad_damaged_after', models.BooleanField(default=False, verbose_name='归还时耳罩破损')),
                ('terminal_used', models.CharField(blank=True, max_length=100, verbose_name='使用终端')),
                ('return_remark', models.TextField(blank=True, verbose_name='归还备注')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='是否超时')),
                ('headphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='headphones.headphone', verbose_name='耳机')),
                ('operator_borrow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_operations', to=settings.AUTH_USER_MODEL, verbose_name='登记人(领出)')),
                ('operator_return', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_operations', to=settings.AUTH_USER_MODEL, verbose_name='登记人(归还)')),
            ],
            options={
                'verbose_name': '领用记录',
                'verbose_name_plural': '领用记录',
                'ordering': ['-borrow_time'],
            },
        ),
        migrations.CreateModel(
            name='AbnormalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abnormal_type', models.CharField(choices=[('low_battery', '连续低电量'), ('earpad_damage', '同批次耳罩破损偏多'), ('overdue', '归还超时'), ('review_missed', '复核遗漏'), ('terminal_conflict', '终端适配冲突')], max_length=30, verbose_name='异常类型')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=20, verbose_name='严重程度')),
                ('description', models.TextField(verbose_name='异常描述')),
                ('detected_time', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
                ('resolved', models.BooleanField(default=False, verbose_name='已处理')),
                ('resolve_remark', models.TextField(blank=True, verbose_name='处理备注')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_records', to='headphones.batch', verbose_name='批次')),
                ('headphone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_records', to='headphones.headphone', verbose_name='耳机')),
            ],
            options={
                'verbose_name': '异常记录',
                'verbose_name_plural': '异常记录',
                'ordering': ['-detected_time'],
            },
        ),
    ]
